name: Build and test
on:
  pull_request:
    branches:
      - 'main'
      - 'ihexon'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'

      - name: Set up Go
        uses: 'actions/setup-go@v5'
        with:
          go-version: '1.23.4'

      - name: Build
        run: make build

  lint:
    runs-on: macos-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

