name: Build and test
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'LICENSE'
      - 'doc/**'
    branches:
      - 'dev'
      - 'main'
      - 'ci'
  pull_request:
    branches:
      - 'dev'
      - 'main'
      - 'ci'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'

      - name: Set up Go
        uses: 'actions/setup-go@v5'
        with:
          go-version: '1.23'

      - name: Build
        run: |
          git log -1
          make clean && make build