name: Release

on:
  push:
    tags:
      - 'v*.*.*-RC*'

permissions:
  contents: write
  id-token: write
  packages: read

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Set up Go
        uses: "actions/setup-go@v5"
        with:
          go-version: '1.23'

      - name: Build
        run: |
          git log -1
          make clean && make build

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: out/bin/*
          generate_release_notes: true
          draft: false
          prerelease: true
          fail_on_unmatched_files: true